// Перечисление для типов операций
public enum ActionType {
    TRAIN_ARRIVAL,
    PASSENGER_TRAIN_ARRIVAL,
    PASSENGER_TRAIN_DEPARTURE,
    TRAIN_DEPARTURE,
    SHUNTING,
    LOCOMOTIVE_CLEANING,
    LOCOMOTIVE_PROVISION,
    ADVANCEMENT,
    LOCOMOTIVE_MOVEMENT_RESERVE,
    SIDETRACK_CLEANING,
    SIDETRACK_PROVISION
}